# Numpy: Arrays and Matrices

In [1]:
import numpy as np

## Create Arrays

In [2]:
d1   = [5,8,4,1,6]
arr1  = np.array(d1)                    # 1D array
d2   = [range(1,5),range(9,13)]         
arr2 = np.array(d2)                     # 2D array
print(arr2)
arr1.tolist()                           # Convert array to list

[[ 1  2  3  4]
 [ 9 10 11 12]]


[5, 8, 4, 1, 6]

In [3]:
# Special Arrays
np.zeros(5)
np.zeros((3,4))
np.ones(10)
np.linspace(0,1,5)
np.logspace(0,3,4)                      # Powers of tens

array([   1.,   10.,  100., 1000.])

In [4]:
int_array = np.arange(10)               # Range based array
float_array = int_array.astype(float)
print(int_array)
print(float_array)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Examine Arrays

In [5]:
arr1.dtype                              # float64
arr2.dtype
arr2.ndim                               # number of dimensions of an array
arr2.shape                              # (2, 4) : (rows, columns)
arr2.size                               # 8: Total no. of elements
len(arr2)                               # size of first axis

2

## Reshaping


In [6]:
arr = np.arange(10)
print(arr.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# Add an axis
a = np.array([0,1])
a_col = a[:,None]                       # Either
a_col = a[:,np.newaxis]                 # Or
print(a_col)

[[0]
 [1]]


In [8]:
# Transpose
print(arr2.T)

[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]]


In [9]:
# Flatten an array

print(arr2.flatten())                         # Either
arr2.ravel()                                  # Or (Flattens dynamically)

[ 1  2  3  4  9 10 11 12]


array([ 1,  2,  3,  4,  9, 10, 11, 12])

## Stack Arrays


In [10]:
# Stacking of differenr arrays in columns
a = np.array([0,1,2])
b = np.array([2,3,4])

print(np.stack((a,b)).T)                     # Notice the 'T' 
np.hstack((a[:,None],b[:,None]))

[[0 2]
 [1 3]
 [2 4]]


array([[0, 2],
       [1, 3],
       [2, 4]])

## Selection


In [11]:
print(arr2)

#Single item
print('Matrix Element (1,0) is:', arr2[1,0])
print('Matrix Element (1,0) is:', arr2[1][0]) # C/C++ like selection

[[ 1  2  3  4]
 [ 9 10 11 12]]
('Matrix Element (1,0) is:', 9)
('Matrix Element (1,0) is:', 9)


### Slicing

In [12]:
########### THINKING OF AN ARRAY AS A MATRIX REALLY HELPS IN FOLLOWING COMMANDS ###########
# Start:Stop:Jump
print(arr2)
print('1:',arr2[0,:])
print('2:',arr2[0,::2])      # Jump 2 steps
print('3:',arr2[0,:3])       # Before index 3
print('4:',arr2[0,3:])       # After indes 3 (includes 3)
print('5:',arr2[:,0])
print(arr2[::-1,1:3])        # Reversed and sliced rows

[[ 1  2  3  4]
 [ 9 10 11 12]]
('1:', array([1, 2, 3, 4]))
('2:', array([1, 3]))
('3:', array([1, 2, 3]))
('4:', array([4]))
('5:', array([1, 9]))
[[10 11]
 [ 2  3]]


### Fancy Indexing

In [13]:
print(arr2)       
print('1:', arr2[:,[1,2]])         # Integer indexing 
print('2:', arr2[arr2 < 10])       # Boolean array indexing

# Modification of an array
arr2[arr2 > 10] = 0
print('3:',arr2)    

[[ 1  2  3  4]
 [ 9 10 11 12]]
('1:', array([[ 2,  3],
       [10, 11]]))
('2:', array([1, 2, 3, 4, 9]))
('3:', array([[ 1,  2,  3,  4],
       [ 9, 10,  0,  0]]))


In [14]:
alph = np.array(['a','b','c','d'])
print('1:',(alph=='a') | (alph=='d'))
print('2:',alph[alph!='a'])

# Modification of an array
alph[alph!='a'] = 'b'
print('3:', alph)
print('4:', np.unique(alph))

('1:', array([ True, False, False,  True]))
('2:', array(['b', 'c', 'd'], dtype='|S1'))
('3:', array(['a', 'b', 'b', 'b'], dtype='|S1'))
('4:', array(['a', 'b'], dtype='|S1'))


## Vectorized Opeartions

In [15]:
n = np.arange(4)
print('0:',n)
print('1:',n**2)
print('2:',np.sqrt(n**2))
print('3:',np.ceil(np.array([2.34, 3.13, 4.89])))
print('4:',np.floor(np.array([2.34, 3.13, 4.89])))
print('5:',np.rint(np.array([2.34, 3.13, 4.89])))
print('6:',np.isnan(0/np.array([2.34, 0, 4.89])))

('0:', array([0, 1, 2, 3]))
('1:', array([0, 1, 4, 9]))
('2:', array([0., 1., 2., 3.]))
('3:', array([3., 4., 5.]))
('4:', array([2., 3., 4.]))
('5:', array([2., 3., 5.]))
('6:', array([False,  True, False]))


/home/amol/.local/lib/python2.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in divide
  


In [16]:
#Euclidean distance between two vectors
v1 = np.random.randn(10)
v2 = np.random.randn(10)
np.sqrt(np.sum((v1-v2)**2))

5.137028081307065

In [17]:
########## VERY IMPORTANT STATISTICAL OPERATIONS ##############

# Maths and Stitistics
rnd = np.random.randn(4,2)
print(rnd)
print('--------------------------------------')
print('1:',rnd.mean())            # Mean
print('2:',rnd.std())             # Standard deviation
print('3:',rnd.argmin())          # Index of minimum value
print('4:',rnd.sum(axis = 0))     # Sum of columns
print('5:',rnd.sum(axis = 1))     # Sum of rows

[[ 0.04172885 -1.41203518]
 [ 1.23354399  0.56124996]
 [ 0.12925685 -0.69922459]
 [-1.66754864  0.3555008 ]]
--------------------------------------
('1:', -0.18219099605726555)
('2:', 0.9340362749640669)
('3:', 6)
('4:', array([-0.26301896, -1.19450901]))
('5:', array([-1.37030633,  1.79479395, -0.56996774, -1.31204785]))


In [18]:
# Boolean array mathods
print('1:',(rnd > 0).sum())        # Number of positive values
print('1:',(rnd > 0).any())        # If any value is true?
print('1:',(rnd > 0).all())        # Are all values true?

('1:', 5)
('1:', True)
('1:', False)


In [19]:
# Random numbers
np.random.seed(12)                 # Set the seed
np.random.rand(4,2)                # Random numbers between 0 and 1
np.random.randn(4,2)               # Gaussian distributed random number N~(0,1)
np.random.randint(1,3,5)           # Random integers (min, max+1, number of points)

array([1, 1, 2, 2, 2])

## Brodcasting
Calculations with arrays of differenrt sizes. Implemented in C (instead of in Python). 

General rules:
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html.

In [20]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10]])
b = np.array([20, 20, 20])

a + b

array([[20, 20, 20],
       [30, 30, 30]])