# Numpy: Arrays and Matrices

In [195]:
import numpy as np

## Create Arrays

In [196]:
d1   = [5,8,4,1,6]
arr1  = np.array(d1)                    # 1D array
d2   = [range(1,5),range(9,13)]         
arr2 = np.array(d2)                     # 2D array
print(arr2)
arr1.tolist()                           # Convert array to list

[[ 1  2  3  4]
 [ 9 10 11 12]]


[5, 8, 4, 1, 6]

In [197]:
# Special Arrays
np.zeros(5)
np.zeros((3,4))
np.ones(10)
np.linspace(0,1,5)
np.logspace(0,3,4)                      # Powers of tens

array([   1.,   10.,  100., 1000.])

In [198]:
int_array = np.arange(10)               # Range based array
float_array = int_array.astype(float)
print(int_array)
print(float_array)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Examine Arrays

In [199]:
arr1.dtype                              # float64
arr2.dtype
arr2.ndim                               # number of dimensions of an array
arr2.shape                              # (2, 4) : (rows, columns)
arr2.size                               # 8: Total no. of elements
len(arr2)                               # size of first axis

2

## Reshaping


In [200]:
arr = np.arange(10)
print(arr.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [201]:
# Add an axis
a = np.array([0,1])
a_col = a[:,None]                       # Either
a_col = a[:,np.newaxis]                 # Or
print(a_col)

[[0]
 [1]]


In [202]:
# Transpose
print(arr2.T)

[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]]


In [203]:
# Flatten an array

print(arr2.flatten())                         # Either
arr2.ravel()                                  # Or (Flattens dynamically)

[ 1  2  3  4  9 10 11 12]


array([ 1,  2,  3,  4,  9, 10, 11, 12])

## Stack Arrays


In [204]:
# Stacking of differenr arrays in columns
a = np.array([0,1,2])
b = np.array([2,3,4])

print(np.stack((a,b)).T)                     # Notice the 'T' 
np.hstack((a[:,None],b[:,None]))

[[0 2]
 [1 3]
 [2 4]]


array([[0, 2],
       [1, 3],
       [2, 4]])

## Selection


In [205]:
print(arr2)

#Single item
print('Matrix Element (1,0) is:', arr2[1,0])
print('Matrix Element (1,0) is:', arr2[1][0]) # C/C++ like selection

[[ 1  2  3  4]
 [ 9 10 11 12]]
Matrix Element (1,0) is: 9
Matrix Element (1,0) is: 9


### Slicing

In [206]:
########### THINKING OF AN ARRAY AS A MATRIX REALLY HELPS IN FOLLOWING COMMANDS ###########
# Start:Stop:Jump
print(arr2)
print('1:',arr2[0,:])
print('2:',arr2[0,::2])      # Jump 2 steps
print('3:',arr2[0,:3])       # Before index 3
print('4:',arr2[0,3:])       # After indes 3 (includes 3)
print('5:',arr2[:,0])
print(arr2[::-1,1:3])        # Reversed and sliced rows

[[ 1  2  3  4]
 [ 9 10 11 12]]
1: [1 2 3 4]
2: [1 3]
3: [1 2 3]
4: [4]
5: [1 9]
[[10 11]
 [ 2  3]]


### Fancy Indexing

In [207]:
print(arr2)       
print('1:', arr2[:,[1,2]])         # Integer indexing 
print('2:', arr2[arr2 < 10])       # Boolean array indexing

# Modification of an array
arr2[arr2 > 10] = 0
print('3:',arr2)    

[[ 1  2  3  4]
 [ 9 10 11 12]]
1: [[ 2  3]
 [10 11]]
2: [1 2 3 4 9]
3: [[ 1  2  3  4]
 [ 9 10  0  0]]


In [208]:
alph = np.array(['a','b','c','d'])
print('1:',(alph=='a') | (alph=='d'))
print('2:',alph[alph!='a'])

# Modification of an array
alph[alph!='a'] = 'b'
print('3:', alph)
print('4:', np.unique(alph))

1: [ True False False  True]
2: ['b' 'c' 'd']
3: ['a' 'b' 'b' 'b']
4: ['a' 'b']


## Vectorized Opeartions

In [209]:
n = np.arange(4)
print('0:',n)
print('1:',n**2)
print('2:',np.sqrt(n**2))
print('3:',np.ceil(np.array([2.34, 3.13, 4.89])))
print('4:',np.floor(np.array([2.34, 3.13, 4.89])))
print('5:',np.rint(np.array([2.34, 3.13, 4.89])))
print('6:',np.isnan(0/np.array([2.34, 0, 4.89])))

0: [0 1 2 3]
1: [0 1 4 9]
2: [0. 1. 2. 3.]
3: [3. 4. 5.]
4: [2. 3. 4.]
5: [2. 3. 5.]
6: [False  True False]


/home/amol/.local/lib/python3.5/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  


In [210]:
#Euclidean distance between two vectors
v1 = np.random.randn(10)
v2 = np.random.randn(10)
np.sqrt(np.sum((v1-v2)**2))

3.752469664897313

In [211]:
########## VERY IMPORTANT STATISTICAL OPERATIONS ##############

# Maths and Stitistics
rnd = np.random.randn(4,2)
print(rnd)
print('--------------------------------------')
print('1:',rnd.mean())            # Mean
print('2:',rnd.std())             # Standard deviation
print('3:',rnd.argmin())          # Index of minimum value
print('4:',rnd.sum(axis = 0))     # Sum of columns
print('5:',rnd.sum(axis = 1))     # Sum of rows

[[ 1.40709829  0.00321688]
 [-0.56455474 -0.11228122]
 [-1.61017387  0.48681308]
 [ 0.56673247  0.26761333]]
--------------------------------------
1: 0.05555802723013889
2: 0.829835899103386
3: 4
4: [-0.20089785  0.64536207]
5: [ 1.41031517 -0.67683596 -1.12336079  0.8343458 ]


In [212]:
# Boolean array mathods
print('1:',(rnd > 0).sum())        # Number of positive values
print('1:',(rnd > 0).any())        # If any value is true?
print('1:',(rnd > 0).all())        # Are all values true?

1: 5
1: True
1: False


In [213]:
# Random numbers
np.random.seed(12)                 # Set the seed
np.random.rand(4,2)                # Random numbers between 0 and 1
np.random.randn(4,2)               # Gaussian distributed random number N~(0,1)
np.random.randint(1,3,5)           # Random integers (min, max+1, number of points)

array([1, 1, 2, 2, 2])

## Brodcasting
Calculations with arrays of differenrt sizes. Implemented in C (instead of in Python). 

General rules:
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html.

In [214]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10]])
b = np.array([20, 20, 20])

a + b

array([[20, 20, 20],
       [30, 30, 30]])

## Excercises